---
- name: Criação das tabelas Iceberg
  hosts: local
  become: false
  gather_facts: false
  roles:
    - role: lambda-tables
      when: acao == 'deploy'

- name: Implementação do Kafka Producer
  hosts: kafka_client
  become: true 
  gather_facts: false
  roles:
    - role: kafka-producer 
      when: acao == 'deploy' 