- name: Criação das tabelas Iceberg e atualização pontual da tabela crypto_assets
  hosts: local
  become: false
  gather_facts: false
  roles:
    - role: lambda
      when: acao == 'deploy'

- name: Implementação do Kafka Producer
  hosts: kafka_client
  become: true 
  gather_facts: false
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  roles:
    - role: kafka-producer 
      when: acao == 'deploy' 
      
- name: Submit Jobs em Spark com gravação no S3
  hosts: emr_s3_client
  become: true 
  gather_facts: false
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  roles:
    - role: spark-submit-s3 
      when: acao == 'deploy' 

- name: Submit Jobs em Spark com gravação no Elastic
  hosts: emr_els_client
  become: true 
  gather_facts: false
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  roles:
    - role: spark-submit-els 
      when: acao == 'deploy'

- name: Cria o dashboard de acompanhamento no Kibana
  hosts: local
  become: false
  gather_facts: false
  roles:
    - role: kibana-dash
      when: acao == 'deploy'