---
- name: Criacao de Recursos na AWS
  hosts: local
  gather_facts: no
  roles:
    - terraform

- name: Configurar instancia EC2 para execucao do Producer Kafka
  hosts: kafka_client
  become: true
  ignore_unreachable: true
  tasks:
    - name: Incluir role do Kafka Producer
      include_role:
        name: kafka-producer
      when: acao == 'deploy'
