- name: Copia o script de execução para o nó master
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/roles/spark-submit-s3-crypto/files/run_spark_s3.sh"
    dest: /tmp/
    mode: '0755'

- name: Define caminhos e nomes de arquivos
  set_fact:
    crypto_jar: "{{ playbook_dir }}/programs/KafkaConsumerCryptoS3-1.0.jar"
    crypto_class: "KafkaConsumerCryptoS3"

- name: Copia o JAR do Crypto para o nó master
  ansible.builtin.copy:
    src: "{{ crypto_jar }}"
    dest: /tmp/KafkaConsumerCryptoS3-1.0.jar
  register: copy_crypto_result
  failed_when: copy_crypto_result is failed

- name: Executa o spark-submit do streaming do Crypto
  ansible.builtin.command: /tmp/run_spark_s3.sh "{{ kafka_bootstrap_server }}" "/tmp/KafkaConsumerCryptoS3-1.0.jar" "{{ crypto_class }}" "/home/hadoop/spark_streaming_crypto.log"
  args:
    chdir: /home/hadoop
  async: 3600
  poll: 0
  changed_when: false
  register: crypto_job_result
  failed_when: crypto_job_result is failed

- name: Aguardar 60 segundos após o lançamento do job Crypto
  ansible.builtin.pause:
    seconds: 60