---
- name: Executa funcao Lambda para criacao das tabelas
  amazon.aws.lambda_execute:
    name: "executa-criacao-tabelas"
  register: lambda_result

- name: Verifica resultado da chamada Lambda se falhou
  debug:
    msg: "Resultado da chamada Lambda: {{ lambda_result }}"
  when: lambda_result.failed

- name: Verifica resultado da chamada Lambda se executou com sucesso
  debug:
    msg: "Função Lambda executada com sucesso: {{ lambda_result }}"
  when: not lambda_result.failed

- name: Executa funcao Lambda para atualizar os icones das moedas em background
  amazon.aws.lambda_execute:
    name: "atualiza-assets-icons"
  async: 3600
  poll: 0
  register: lambda_assets_result

- name: Verificar status da função Lambda
  debug:
    msg: "Resultado da chamada Lambda (assets): {{ lambda_assets_result }}"
  when: lambda_assets_result.changed
